name: Cancel Duplicates
on:
  workflow_dispatch:

jobs:
  cancel-duplicate-runs:
    name: Cancel duplicate workflow runs
    runs-on: ubuntu-20.04
    steps:
      - name: Check number of queued tasks
        id: check_queued
        run: |
          count=5
          echo "Found $count unfinished jobs."
          echo "::set-output name=count::$count"

    
